# Generated by Django 2.1.7 on 2020-09-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_amount',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_company',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_currency',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_customer_number',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_date',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_dated',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_notice',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_number',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='doc_search_key',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='lates_file',
        ),
        migrations.RemoveField(
            model_name='myvideo',
            name='old_files',
        ),
    ]
