# Generated by Django 3.0.5 on 2020-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_to_one_share_uid',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
