# Generated by Django 2.1.7 on 2020-09-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200904_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myvideo',
            name='user',
        ),
    ]
