"""
Django settings for vip_number project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_74nhp_=h9cs=*hdlz+9rdf!hi9)1yz^)p^c2baghro^o5#n63'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'


# Application definition

INSTALLED_APPS = [
    'jet',
    'jet.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'file_management.users',
    # 'file_management.mydocuments',
    # 'sellers',
    # 'file_management.category_tag',
    # 'file_management.category_numbers',
    # 'file_management.number',
    'tagconstants',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'file_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'file_management.wsgi.application'

# Constants
TAG_CONSTANTS = {
    'PROJECT_NAME': 'vipnumbersshop.com',
    'COMPANY_NAME': 'VIP Number Shop',
    'PROJECT_URL': 'http://localhost:8000/'
}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {},
#     'auth_db': {
#         'NAME': 'auth_db',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'mysql_user',
#         'PASSWORD': 'swordfish',
#     },
#     'primary': {
#         'NAME': 'primary',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'mysql_user',
#         'PASSWORD': 'spam',
#     },
#     'replica1': {
#         'NAME': 'replica1',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'mysql_user',
#         'PASSWORD': 'eggs',
#     },
#     'replica2': {
#         'NAME': 'replica2',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'mysql_user',
#         'PASSWORD': 'bacon',
#     },
# }

# DB_PATH = BASE_DIR
# DATABASE_ROUTERS = ['users.routers.MyApp2Router']

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'auth_db': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'auth_db.sqlite3'),
#     },
#     'primary': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'primary.sqlite3'),
#     },
#     'replica1': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'replica1.sqlite3'),
#     },
#     'replica2': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'replica2.sqlite3'),
#     },
#     'sheela': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'sheela.sqlite3'),
#     }, 
#     'my_db_2': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db3.sqlite3'),
#     },
# }



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    # '/var/www/html/p_project/pureloan/static/',
)

DIRECTORY = os.path.join(BASE_DIR, 'documents/')

PATH = os.path.join(BASE_DIR)

MEDIA_URL =  '/documents/'
MEDIA_ROOT =  DIRECTORY

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC = os.path.join(BASE_DIR, 'static')
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True
JET_DEFAULT_THEME = 'default'

# SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.vipnumbershop.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'info@vipnumbershop.com'
# DEFAULT_FROM_EMAIL = 'info@vipnumbershop.com'
# EMAIL_HOST_PASSWORD = 'vipnumber1234'
# # AUTH_USER_MODEL = 'users.User'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'smartlegal005@gmail.com'
# DEFAULT_FROM_EMAIL = 'smartlegal005@gmail.com'
# EMAIL_HOST_PASSWORD = 'Abcd@123'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.ionos.de'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'register@invocont.com'
DEFAULT_FROM_EMAIL = 'register@invocont.com'
EMAIL_HOST_PASSWORD = 'AXY735@AAE!2020ae'

#Flash Messaege settings
# MESSAGE_LEVEL = message_constants.DEBUG
MESSAGE_LEVEL = 10


from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# from file_management.users.models import User

# users = AUTH_USER_MODEL.objects.all()
# from django.contrib.auth import get_user_model
# User = get_user_model()
# print("=================================")
# print(User)
# print(BASE_DIR)
# print(DIRECTORY)
# print(DIRECTORY(__file__))
# print(AUTH_USER_MODEL.objects.all())
# print("=================================")